version: 2

build:
  os: ubuntu-20.04
  image: testing

sphinx:
  configuration: code/docs/source/conf.py

python:
  version: "3.8"
  install:
    - method: pip
      path: code
    - requirements: code/docs/requirements.txt