version: 2

build:
  os: ubuntu-20.04
  tools: 
    python: "3.10"

sphinx:
  configuration: code/docs/source/conf.py

python:
  version: "3.10"
  install:
    - method: pip
      path: code
    - requirements: code/docs/requirements.txt