name: tests

on:
  push:
    branches:
      - master
      - stable
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/tests.yml"
      - "Makefile"
      - "PyNetworkD3/**/*.py"
      - "tests/**/*.py"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install Poetry
        run: make get-poetry

      - name: Add system path to Poetry
        run: echo $HOME/.poetry/bin >> $GITHUB_PATH

      - name: Set up Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          key: poetry-cache-v1-${{ hashFiles('**/poetry.lock') }}
          path: .venv

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Run Pytest
        run: make tests

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
